-- 1. Create province,city Master table
CREATE TABLE dim.reference_city (
    city NVARCHAR(50) PRIMARY KEY,
    province VARCHAR(100)
);
GO

INSERT INTO dim.reference_city (city, province)
VALUES 
('Pematangsiantar', 'Sumatera Utara'),
('Serang', 'Banten'),
('Singkawang', 'Kalimantan Barat'),
('Padang Sidempuan', 'Sumatera Utara'),
('Pangkalpinang', 'Kepulauan Bangka Belitung'),
('Tidore Kepulauan', 'Maluku Utara'),
('Magelang', 'Jawa Tengah'),
('Padangpanjang', 'Sumatera Barat'),
('Pariaman', 'Sumatera Barat'),
('Semarang', 'Jawa Tengah'),
('Tanjungbalai', 'Sumatera Utara'),
('Langsa', 'Aceh'),
('Binjai', 'Sumatera Utara'),
('Bandung', 'Jawa Barat'),
('Tegal', 'Jawa Tengah'),
('Pekanbaru', 'Riau'),
('Bitung', 'Sulawesi Utara'),
('Banjar', 'Jawa Barat'),
('Batu', 'Jawa Timur'),
('Bima', 'Nusa Tenggara Barat'),
('Purwokerto', 'Jawa Tengah'),
('Sukabumi', 'Jawa Barat'),
('Kota Administrasi Jakarta Selatan', 'DKI Jakarta'),
('Payakumbuh', 'Sumatera Barat'),
('Sorong', 'Papua Barat Daya'),
('Mataram', 'Nusa Tenggara Barat'),
('Medan', 'Sumatera Utara'),
('Banjarbaru', 'Kalimantan Selatan'),
('Banjarmasin', 'Kalimantan Selatan'),
('Palangkaraya', 'Kalimantan Tengah'),
('Sabang', 'Aceh'),
('Batam', 'Kepulauan Riau'),
('Metro', 'Lampung'),
('Bau-Bau', 'Sulawesi Tenggara'),
('Banda Aceh', 'Aceh'),
('Denpasar', 'Bali'),
('Meulaboh', 'Aceh'),
('Sungai Penuh', 'Jambi'),
('Mojokerto', 'Jawa Timur'),
('Subulussalam', 'Aceh'),
('Padang', 'Sumatera Barat'),
('Tarakan', 'Kalimantan Utara'),
('Manado', 'Sulawesi Utara'),
('Cimahi', 'Jawa Barat'),
('Bengkulu', 'Bengkulu'),
('Probolinggo', 'Jawa Timur'),
('Kota Administrasi Jakarta Utara', 'DKI Jakarta'),
('Bandar Lampung', 'Lampung'),
('Bekasi', 'Jawa Barat'),
('Kendari', 'Sulawesi Tenggara'),
('Tebingtinggi', 'Sumatera Utara'),
('Lhokseumawe', 'Aceh'),
('Palu', 'Sulawesi Tengah'),
('Surabaya', 'Jawa Timur'),
('Sibolga', 'Sumatera Utara'),
('Sawahlunto', 'Sumatera Barat'),
('Prabumulih', 'Sumatera Selatan'),
('Madiun', 'Jawa Timur'),
('Bogor', 'Jawa Barat'),
('Balikpapan', 'Kalimantan Timur'),
('Salatiga', 'Jawa Tengah'),
('Tasikmalaya', 'Jawa Barat'),
('Surakarta', 'Jawa Tengah'),
('Pasuruan', 'Jawa Timur'),
('Palopo', 'Sulawesi Selatan'),
('Bukittinggi', 'Sumatera Barat'),
('Jayapura', 'Papua'),
('Tangerang', 'Banten'),
('Malang', 'Jawa Timur'),
('Tomohon', 'Sulawesi Utara'),
('Pekalongan', 'Jawa Tengah'),
('Bontang', 'Kalimantan Timur'),
('Lubuklinggau', 'Sumatera Selatan'),
('Gorontalo', 'Gorontalo'),
('Tual', 'Maluku'),
('Cilegon', 'Banten'),
('Kota Administrasi Jakarta Barat', 'DKI Jakarta'),
('Cirebon', 'Jawa Barat'),
('Pagaralam', 'Sumatera Selatan'),
('Kota Administrasi Jakarta Timur', 'DKI Jakarta'),
('Kediri', 'Jawa Timur'),
('Pontianak', 'Kalimantan Barat'),
('Kotamobagu', 'Sulawesi Utara'),
('Ternate', 'Maluku Utara'),
('Ambon', 'Maluku'),
('Tanjungpinang', 'Kepulauan Riau'),
('Makassar', 'Sulawesi Selatan'),
('Parepare', 'Sulawesi Selatan'),
('Blitar', 'Jawa Timur'),
('Kota Administrasi Jakarta Pusat', 'DKI Jakarta'),
('Depok', 'Jawa Barat'),
('Jambi', 'Jambi'),
('Kupang', 'Nusa Tenggara Timur'),
('Tangerang Selatan', 'Banten'),
('Samarinda', 'Kalimantan Timur'),
('Yogyakarta', 'DI Yogyakarta'),
('Solok', 'Sumatera Barat'),
('Palembang', 'Sumatera Selatan'),
('Dumai', 'Riau');
GO

--2.Create relationship between Fact table and Reference city
ALTER TABLE fact.sales_transactions
ADD CONSTRAINT FK_FactSales_RefCity
FOREIGN KEY (city) REFERENCES dim.reference_city(city);
GO