--CREATE OR ALTER VIEW V_base AS
SELECT
    f.transaction_id,
    f.transaction_date,
    d.date_year,
    d.date_month,
    d.date_month_name,
    d.date_day,
    d.date_day_name,
    d.date_quarter,
    f.order_time,
    f.platform,
    f.order_source,
    f.sales_channel_type,
    f.cashier_or_host,
    f.customer_id,
    f.unique_customer_id,
    f.unique_customer_id AS customer_key,
    f.customer_name,
    f.customer_gender,
    f.customer_age,
    f.city,
    f.province,
    f.membership_tier,
    f.product_code,
    p.product_name,
    p.category,
    p.sub_category,
    p.shade,
    p.finish_type,
    p.skin_type_target,
    p.size_ml,
    p.launch_year,
    p.product_status,
    p.production_cost,
    p.selling_price,
    p.brand,
    p.local_or_import,
    p.halal_certified,
    p.vegan_product,
    p.bpom_registered,
    p.supplier_name,
    p.warehouse_location,
    p.stock_qty,
    p.reorder_point,
    p.rating_average,
    p.review_count,
    f.quantity,
    f.quantity_sold,
    f.gross_sales,
    f.discount_amount,
    f.net_sales,
    f.shipping_cost,
    f.platform_fee,
    CASE WHEN f.delivered_flag= 1 THEN f.net_sales-f.platform_fee-(p.production_cost*f.quantity_sold) ELSE 0 END AS realized_profit_after_fee,
    f.payment_method,
    f.voucher_used,
    f.campaign_name,
    f.warehouse_origin,
    f.delivery_status,
    f.delivery_days,
    f.customer_rating,
    f.returned_flag,
    f.return_reason,
    f.Cancelled_flag,
    f.delivered_flag

FROM fact.sales_transactions AS f
LEFT JOIN dim.date AS d
    ON f.transaction_date = d.transaction_date
LEFT JOIN dim.products AS p
    ON f.product_code = p.product_code;
GO